#!/bin/sh

# debug
yabai -m config debug_output on

# bar settings
yabai -m config status_bar                   off
#yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
#yabai -m config status_bar_icon_font         "FontAwesome:Regular:12.0"
#yabai -m config status_bar_background_color  0xff202020
#yabai -m config status_bar_foreground_color  0xffa8a8a8
#yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
#yabai -m config status_bar_power_icon_strip   
#yabai -m config status_bar_space_icon        
#yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             first_child

yabai -m config window_shadow                on
#yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
#yabai -m config window_border                off
#yabai -m config window_border_width          2
#yabai -m config window_border_radius         -1.0

#yabai -m config active_window_border_topmost on
#yabai -m config active_window_border_color   0xFFF07178
#yabai -m config insert_window_border_color   0xFFF78c6c
#yabai -m config normal_window_border_color   0x00010101
yabai -m config active_window_opacity        1.00
yabai -m config normal_window_opacity        0.95

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# window rules
manage_off='()'

manage_off="$manage_off"'|(Alacritty)'
manage_off="$manage_off"'|(Chromium)'
manage_off="$manage_off"'|(Microsoft .*)'

yabai -m rule --add app!='^('"$manage_off"')$' manage=off

# signals
yabai -m signal --add event=window_destroyed action='yabai -m query --windows --window >/dev/null || yabai -m window --focus mouse || yabai -m window --focus first'
yabai -m signal --add event=application_terminated action='yabai -m query --windows --window >/dev/null || yabai -m window --focus mouse || yabai -m window --focus first'
